### ISSUE TITLE
Feature Idea: Kino.ignore to avoid an Elixir cell outputting anything

### ISSUE THREAD

**Issue by mcintyre94** [elixir-nx/kino#29]
Sometimes an Elixir cell in a LiveBook has a pretty meaningless output and it's just the side effects that you want - eg. setting variables or rendering something else. One option would be to put an `:ok` or `nil` at the end so that becomes the output, but that's a bit unclear about intent and would be a bit annoying with the export to script feature that's been talked about.

One example is where you use `Kino.render()` with a VegaLite graph and then add data to it in the loop - I end up with output of a long list like `[:ok, :ok, ...]

Would it make sense to instead be able to pipe to a Kino function that returns what's piped in but renders as nothing?

Two examples where I'd like to use this:

```elixir
url = IO.gets("URL: ") |> String.trim()
{iterations, _} = IO.gets("Iterations: ") |> String.trim() |> Integer.parse() |> Kino.ignore
```

And

```elixir
widget =
  Vl.new(width: 600, height: 400, title: "Performance for #{url}")
  ...
  |> Kino.VegaLite.new()
  |> Kino.render()

(for i <- 1..iterations do
  point = %{iteration: i, ...}
  Kino.VegaLite.push(widget, point)
end) |> Kino.ignore
```

**Comment by josevalim** [comment]
I thought about this a couple times already and I think simply returning the atom :ok in the end is enough. Sure, there is still some output, but it is minimal.

the other option is to configure in the UI to hide output from cells…

**Comment by mcintyre94** [comment]
Yep fair enough, it's definitely minor either way! Configuring in the UI per cell would probably be the most flexible/general solution, but does seem a bit overkill at least for my use case :) I'll close this for now because it sounds like anything that might happen in future would be in livebook not kino.

**Comment by jonatanklosko** [comment]
Yeah, I thought about this as well and returning `:ok` seems alright to me. Even with `Kino.ignore()` that's an additional line/call and sounds like an overkill to me. If you're really motivated you can return `:"do not show this result in output"` as the cell result, and it's not gonna show up (that's what `IEx.Helpers` often return).

As for hiding the output via UI, we could have a collapse button and we would persist that a cell output is collapsed (otherwise it kinda kills the point). I'm not entirely sure if that's something we want or not though.
